version: '3.8'

services:
  # The Python ML API Service
  python-api:
    build: .
    container_name: python-api-compose
    ports:
      - "8000:80"

  # The C# Backend Service
  csharp-backend:
    build: ./ChurnPlatform.Backend
    container_name: csharp-backend-compose
    ports:
      - "8001:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    # Add this depends_on so the C# app waits for the Python API to be healthy
    depends_on:
      - python-api