services:
  python-api:
    image: devinbjackson/churn-api:latest
    container_name: python-api-prod
    ports:
      - "8000:80"

  csharp-backend:
    image: devinbjackson/churn-backend:latest
    container_name: csharp-backend-prod
    ports:
      - "8001:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - python-api
      - db

  # The database service is included for local testing of production images
  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTG-RES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=churn_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: