# .github/workflows/main.yml

name: Build, Push, and Deploy to Azure

on:
  push:
    branches: [ "master" ]

env:
  PYTHON_APP_NAME: churn-api-devbjackson
  CSHARP_APP_NAME: churn-backend-devbjackson

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Python API
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/churn-api:latest

      - name: Build and push C# Backend
        uses: docker/build-push-action@v5
        with:
          context: ./ChurnPlatform.Backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/churn-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push # This job runs only after the build-and-push job succeeds
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Python API to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.PYTHON_APP_NAME }}
          images: ${{ secrets.DOCKERHUB_USERNAME }}/churn-api:latest

      - name: Deploy C# Backend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.CSHARP_APP_NAME }}
          images: ${{ secrets.DOCKERHUB_USERNAME }}/churn-backend:latest

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-and-push # Runs after the backend images are built
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Azure Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name churnstorage1175 --source ./frontend/build --destination '$web' --overwrite